apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: nbalf3tcj-go 
  janus-idp.io/tekton: nbalf3tcj-go
  backstage.io/kubernetes-id: nbalf3tcj-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: nbalf3tcj-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml