apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: nbalf3tcj-go-gitops
  description: This is GitOps manifest for nbalf3tcj-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=nbalf3tcj-go
    backstage.io/kubernetes-id: nbalf3tcj-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: nbalf3tcj-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:nbalf3tcj-go
